from .pre_id import PreId
from .pre_siniestros import PreSiniestros
from .pre_features import PreFeatures
from .pre_autorizados import PreAutorizados
from .tipo_clientes import TipoClientes
from .tipo_documentos import TipoDocumento
from .tipo_features import TipoFeature
from .tipo_roles import TipoRol
from .tipo_siniestros import TipoSiniestro
from .out_nodos import OutNodos
from .out_leads import OutLeads
from .out_cards import OutCards
from .clientes import Clientes
from .distritos import Distritos
from .fueros import Fueros
from .provincias import Provincias
from .juzgados import Juzgados
from .vehiculos import Vehiculos
from .personas import Personas
from .documentos import Documentos
from .features import Features
from .siniestros import Siniestros
from .roles import Roles
from .db import *

